# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: B. Williams
email: 
description: Personal Website
baseurl: ""                                    # leave empty for username.github.io, or "/repo-name" for project sites
url: ""                                        # GitHub Pages will set this automatically
image: /assets/img/homepage-preview.png        # used to generate site link preview
image_alt: B. Williams portfolio homepage              # image description

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#
author: B. Williams
profile_image: /assets/img/avatar/avatar.jpeg
occupation: 
snippet:
twitter: 
github: BWilliams003
linkedin: 
stackoverflow: 
website: 
codepen: 
medium: 
email: 
keybase: 
pgp: 
ctftime: 
phonenumber: 

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

tags:  post jekyll styleguide ipsum
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: false                                     # Used to enable comments on blog posts
gitalk_client_id:             
gitalk_client_secret:    
gitalk_repo:
gitalk_owner: 
gitalk_admin: 
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#00334e"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#00334e"
color-scheme: "#00334e"                              # options: demo | changes color scheme based on preset values 
card-color: "#00334e"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
animate: true                                        # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option: education                               # options: education, skills, timeline

# =======================================#          # These  settings are for demo purposes only, things like 
# -----------HELP SETTINGS---------------#          #     popup toasts and tooltips designed to help new 
#========================================#          #     developers as they look into using this theme      
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

collections:
  courses:
    output: true
    permalink: /courses/:name.html
  skills:
    output: true
    permalink: /skills/:name.html
  cyse201s_journals:
    output: true
    permalink: /cyse-201s/journals/:name.html
  cyse200t_articles:
    output: true
    permalink: /cyse-200t/articles/:name.html

include:
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
font_awesome_id: 32a2b2a489                       # Register for free at https://fontawesome.com/ to get your id


# =======================================#        # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-site-verification:                         #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                              #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                       # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                    # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                           #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                                   # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                                  # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                        # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                          # Facebook OpenGraph 




pgp-key: ""